```{r}
library(caret)
library(dplyr)
library(cvms)
library(tibble)
library(ROCR)
```

```{r}
df <- read.csv('../data/diabetes_binary_5050split_health_indicators_BRFSS2015.csv')
set.seed(123) 
train_indices <- createDataPartition(df$Diabetes_binary, p = 0.8, list = FALSE)
train_data <- df[train_indices, ]
test_data <- df[-train_indices, ]
```


```{r}
fit1 <- glm(Diabetes_binary~., data=train_data, family = "binomial")
summary(fit1)
```

remove the unnecessary variables (Smoker, PhysActivity, Fruits, AnyHealthcare, NoDocbcCost)

```{r}
fit2 <- glm(Diabetes_binary~HighBP + HighChol + CholCheck + BMI + Stroke + HeartDiseaseorAttack + Veggies + HvyAlcoholConsump + GenHlth + MentHlth + PhysHlth + DiffWalk + Sex + Age + Education + Income, data=train_data, family = "binomial")
summary(fit2)
```

```{r}
pred1 <- predict(fit2, newdata = test_data, type = "response")
pred1_factor <- ifelse(pred1 > 0.5, "1", "0") %>% factor

cm <- confusionMatrix(pred1_factor, as.factor(test_data$Diabetes_binary))
draw_confusion_matrix <- function(cm) {

  layout(matrix(c(1,1,2)))
  par(mar=c(2,2,2,2))
  plot(c(100, 345), c(300, 450), type = "n", xlab="", ylab="", xaxt='n', yaxt='n')
  title('CONFUSION MATRIX', cex.main=2)

  # create the matrix 
  rect(150, 430, 240, 370, col='#3F97D0')
  text(195, 435, 'Class1', cex=1.2)
  rect(250, 430, 340, 370, col='#F7AD50')
  text(295, 435, 'Class2', cex=1.2)
  text(125, 370, 'Predicted', cex=1.3, srt=90, font=2)
  text(245, 450, 'Actual', cex=1.3, font=2)
  rect(150, 305, 240, 365, col='#F7AD50')
  rect(250, 305, 340, 365, col='#3F97D0')
  text(140, 400, 'Class1', cex=1.2, srt=90)
  text(140, 335, 'Class2', cex=1.2, srt=90)

  # add in the cm results 
  res <- as.numeric(cm$table)
  text(195, 400, res[1], cex=1.6, font=2, col='white')
  text(195, 335, res[2], cex=1.6, font=2, col='white')
  text(295, 400, res[3], cex=1.6, font=2, col='white')
  text(295, 335, res[4], cex=1.6, font=2, col='white')

  # add in the specifics 
  plot(c(100, 0), c(100, 0), type = "n", xlab="", ylab="", main = "DETAILS", xaxt='n', yaxt='n')
  text(10, 85, names(cm$byClass[1]), cex=1.2, font=2)
  text(10, 70, round(as.numeric(cm$byClass[1]), 3), cex=1.2)
  text(30, 85, names(cm$byClass[2]), cex=1.2, font=2)
  text(30, 70, round(as.numeric(cm$byClass[2]), 3), cex=1.2)
  text(50, 85, names(cm$byClass[5]), cex=1.2, font=2)
  text(50, 70, round(as.numeric(cm$byClass[5]), 3), cex=1.2)
  text(70, 85, names(cm$byClass[6]), cex=1.2, font=2)
  text(70, 70, round(as.numeric(cm$byClass[6]), 3), cex=1.2)
  text(90, 85, names(cm$byClass[7]), cex=1.2, font=2)
  text(90, 70, round(as.numeric(cm$byClass[7]), 3), cex=1.2)

  # add in the accuracy information 
  text(30, 35, names(cm$overall[1]), cex=1.5, font=2)
  text(30, 20, round(as.numeric(cm$overall[1]), 3), cex=1.4)
  text(70, 35, names(cm$overall[2]), cex=1.5, font=2)
  text(70, 20, round(as.numeric(cm$overall[2]), 3), cex=1.4)
}  

draw_confusion_matrix(cm)

```

···{r}

```{r}
diabetes <- read.csv("../data/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
head(diabetes,10)
hist(diabetes$Diabetes_binary)
diabetes$Diabetes_binary <- as.factor(diabetes$Diabetes_binary)
diabetes$HighBP <- as.factor(diabetes$HighBP)
diabetes$HighChol <- as.factor(diabetes$HighChol)
diabetes$CholCheck <- as.factor(diabetes$CholCheck)
diabetes$Smoker <- as.factor(diabetes$Smoker)
diabetes$Stroke <- as.factor(diabetes$Stroke)
diabetes$HeartDiseaseorAttack <- as.factor(diabetes$HeartDiseaseorAttack)
diabetes$PhysActivity <- as.factor(diabetes$PhysActivity)
diabetes$Fruits <- as.factor(diabetes$Fruits)
diabetes$Veggies <- as.factor(diabetes$Veggies)
diabetes$HvyAlcoholConsump <- as.factor(diabetes$HvyAlcoholConsump)
diabetes$AnyHealthcare <- as.factor(diabetes$AnyHealthcare)
diabetes$NoDocbcCost <- as.factor(diabetes$NoDocbcCost)
diabetes$DiffWalk <- as.factor(diabetes$DiffWalk)
diabetes$Sex <- as.factor(diabetes$Sex)

```



```{r}
#Initial tree

tree.Diabetes_binary=tree::tree(Diabetes_binary~.,data=diabetes)

summary(tree.Diabetes_binary)
plot(tree.Diabetes_binary)
text(tree.Diabetes_binary,pretty=0) #annotate
```


```{r}
library(caret)

# assume that mydata is the data frame you want to split
set.seed(123)  # for reproducibility
train_indices <- createDataPartition(diabetes$Diabetes_binary, p = 0.8, list = FALSE)
train_data <- diabetes[train_indices, ]
test_data <- diabetes[-train_indices, ]



```

```{r}
library(rpart)
library(tree)
library(rattle)
library(visNetwork)
tree.Diabetes_binary <- tree(Diabetes_binary~.,data=train_data)
summary(tree.Diabetes_binary)
tree.Diabetes_binary2 <- rpart(Diabetes_binary~.,data=train_data)
fancyRpartPlot(tree.Diabetes_binary2)
visTree(tree.Diabetes_binary2)

```
```{r}

library(tidyverse)

yhat <- predict(tree.Diabetes_binary,newdata=test_data)
yhat <- as.factor(if_else(yhat[,1] >=0.5, 0, 1))
cm <- confusionMatrix(yhat, test_data$Diabetes_binary)

yhat2 <- predict(tree.Diabetes_binary2,newdata=test_data)
yhat2 <- as.factor(if_else(yhat2[,1] >=0.5, 0, 1))
cm2 <- confusionMatrix(yhat2, test_data$Diabetes_binary)


```
```{r}
# Print the confusion matrices
print(cm)
print(cm2)

```
```{r}
library(randomForest)
set.seed(1)
rf.Diabetes_binary <- randomForest(Diabetes_binary~.,data=train_data,mtry=4,importance=TRUE)
rf.Diabetes_binary
yhat.rf = predict(rf.Diabetes_binary,newdata=test_data)
```

```{r}
tree <- getTree(rf.Diabetes_binary, k=1, labelVar=TRUE)
plot(tree)
```

```{r}
roc3 <- read.csv('../res_gnn.csv')
roc4 <- read.csv('../res_mlp.csv')
roc5 <- read.csv('../res_cnn.csv')

```

```{r}
library(pROC)

roc1 <- roc(test_data$Diabetes_binary, pred1)
roc2 <- roc(test_data$Diabetes_binary, as.numeric(yhat.rf))
roc3 <- roc(roc3$y_true, roc3$y_pred)
roc4 <- roc(roc4$y_true, roc4$y_pred)
roc5 <- roc(roc5$y_true, roc5$y_pred)

#create ROC plot
plot(roc1, main = "ROC", col = 'red')
lines(roc2, col = 'blue')
lines(roc3, col = 'orange')
lines(roc4, col = 'green')
lines(roc5, col = 'purple')


legend(1.5,1,legend=c("Logistic Regression", "Random Forest", 'GNN', 'MLP', 'CNN'),
       col=c("red", "blue", "orange", "green","purple"), lty=1:1, cex=0.8)
```


```{r}
library(caret)
library(dplyr)
library(ggpubr)

lrimp <- varImp(fit1, scale = FALSE)
lrimp <- cbind(newColName = rownames(lrimp), lrimp)
rownames(lrimp) <- 1:nrow(lrimp)
lrimp <- lrimp[order(lrimp$Overall, decreasing = TRUE), ]
lrimp <- lrimp %>% slice(1:10)

rfimp <- varImp(rf.Diabetes_binary, scale = FALSE)
rfimp <- cbind(newColName = rownames(rfimp), rfimp)
rownames(rfimp) <- 1:nrow(rfimp)
rfimp <- rfimp[order(rfimp$`0`, decreasing = TRUE), ]
rfimp <- rfimp %>% slice(1:10)


p<-ggplot(data=lrimp, aes(x=reorder(newColName, Overall), y=Overall)) +
  geom_col()+ coord_flip() + labs(x= "Feature Name", y = "LR Feature Importance")
p 

pp<-ggplot(data=rfimp, aes(x=reorder(newColName, `0`), y=`0`)) +
  geom_col() + coord_flip() + labs(x= "Feature Name", y = "RF Feature Importance")
pp 

ggarrange(p, pp,ncol = 2, nrow = 2)
```































